name: Deploy Website to S3

on:
  push:
    branches:
      - main 
    paths:
      - "frontend/website/**" 
      - ".github/workflows/website.yaml"
env:
  AWS_REGION : "us-east-1"
  WEBSITE_DIRECTORY: "frontend/website"
  S3_BUCKET_NAME: "oussamaachour.com"

permissions:
  id-token: write   # This is required for requesting the JWT
  contents: write    # This is required for actions/checkout

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # - name: Install AWS CLI
      #   run: |
      #     sudo apt-get update
      #     sudo apt-get install -y awscli

      #We use an IAM role to connect GitHub Actions to actions in AWS (more secure than storing aws credentials on GitHub, via GitHub Secrets)
      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v1.7.0
        with:
          role-to-assume: arn:aws:iam::328014421429:role/github-actions-website-s3
          aws-region: ${{ env.AWS_REGION }}

      - name: Deploy to S3
        run: |
          aws s3 sync $WEBSITE_DIRECTORY s3://$S3_BUCKET_NAME --delete        
