name: Deploy Website to S3

on:
  push:
    branches:
      - main  # Change this to match your main branch name
env:
  WEBSITE_DIRECTORY: "../../../frontend/personal-website"
  S3_BUCKET_NAME: "ouss-website-bucket"
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install AWS CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y awscli
      - name : Show aws s3 cmd 
        run : | 
          echo :"aws s3 sync $LOCAL_WEBSITE_DIRECTORY s3://$S3_BUCKET_NAME --delete"

      - name: Configure AWS credentials
        run: | 
          aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }} && aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      - name: Deploy to S3
        run: |
          aws s3 sync $WEBSITE_DIRECTORY s3://$S3_BUCKET_NAME --delete          
